name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: asciidoctor/asciidoctor-action@v2
        with:
          source_dir: .
          source_file: index.adoc
          destination_dir: ./build/html
          backend: html5
          safe: unsafe
          attributes: |
            imagesdir=./images
            kroki-fetch-diagram=true
            kroki-server-url=https://kroki.io
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
