name: Deployment
on:
  release:
    types: [created]
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build PDF
        uses: asciidoctor/asciidoctor-action@v2
        with:
          source_dir: .
          source_file: index.adoc
          destination_dir: ./build/pdf
          backend: pdf
          safe: unsafe
          attributes: |
            imagesdir=./images
            kroki-fetch-diagram=true
            kroki-server-url=https://kroki.io
      - name: Upload PDF to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/pdf/index.pdf
          asset_name: documentation.pdf
          asset_content_type: application/pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
